### PR TITLE
Correct package name

### PR DESCRIPTION
**Pull request by rupl**
Package name in https://github.com/fourkitchens/saucier/blob/master/package.json#L2 has not been updated to Saucier.

### CODE REVIEW

**Comment by rupl** [comment]
I would have just changed it but unfortunately: https://www.npmjs.com/package/saucier

**Comment by rupl** [comment]
also it says `private: true` ??

**Comment by rupl** [comment]
Some ideas:
- `drupal-saucier` — npm recommends you avoid prefixes like `node-` but I think drupal is appropriate because it's not a given in the npm world like `node-` would be.
- `saucier-core` — could be good because then if someone writes an add-on the namespace is obvious. Also avoids the tool-specific issue I noted for `drupal-saucier`

I am assuming namespace must be available on npmjs.com, these are both available right now.

**Comment by mattgrill** [comment]
:+1: on `saucier-core`

**Pull request merged**
